version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: danhvt
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports: 
      - '15432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    image: 'redis'
    container_name: 'redis'
    restart: always
    volumes:
      - ./redis:/data
    ports: 
      - '16379:6379'
  web:
    build: ./frontend
    container_name: orders_web
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3938:80'
  orders_app:
    build: ./backend/orders-app
    # image: "node:15"
    restart: always
    container_name: orders_app
    # working_dir: /home/node/app
    volumes:
      - ./backend/orders-app:/home/node/app
    environment: 
      - NPM_CONFIG_LOGLEVEL=info
    ports: 
      - '3939:3000'
    depends_on:
      - redis
      - db
    links:
      - db
    # command: 'npm run start:dev'
  payments_app:
    build: ./backend/payments-app
    # image: "node:15"
    container_name: payments_app
    restart: always
    # working_dir: /home/node/app
    volumes:
      - ./backend/payments-app:/home/node/app
    environment: 
      - NPM_CONFIG_LOGLEVEL=info
    ports: 
      - '3940:3000'
    depends_on:
      - redis
    # command: 'npm run start:dev'

# volumes:
#   db:
#     name: db

