version: "3"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: danhvt
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports: 
      - '15432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: 'redis'
    restart: always
    ports: 
      - '16379:6379'
  orders_app:
    build: ./backend/orders-app
    restart: always
    ports: 
      - '3001:3000'
    links:
      - 'postgres'
      - 'redis'

