version: "3"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: danhvt
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports: 
      - '15432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: 'redis'
    container_name: 'redis'
    restart: always
    volumes:
      - ./redis:/data
    ports: 
      - '16379:6379'
  orders_app:
    # build: ./backend/orders-app
    image: "node:15"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./backend/orders-app:/home/node/app
    environment: 
      - NPM_CONFIG_LOGLEVEL=info
    ports: 
      - '3939:3000'
    depends_on:
      - redis
      - postgres
    links:
      - 'postgres'
    command: 'npm run start:dev'
  payments_app:
    # build: ./backend/orders-app
    image: "node:15"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./backend/payments-app:/home/node/app
    environment: 
      - NPM_CONFIG_LOGLEVEL=info
    ports: 
      - '3940:3000'
    depends_on:
      - redis
    command: 'npm run start:dev'

